config/routes.rb
Rails.application.routes.draw do

  root to: "application#application"
  post '/ipnlistener', to: 'paypal#notify'
  namespace :billing do 
    post '/braintree_listener', to: 'braintree#webhooks'
  end

  scope :api, defaults: { format: :json } do
    devise_for :members, skip: [:registrations]
    devise_scope :member do
       post "members", to: "registrations#create"
       post '/send_registration', to: 'registrations#new'
    end
    resources :invoice_options, only: [:index]

    authenticate :member do
      resources :members, only: [:show, :index, :update]
      resources :rentals, only: [:show, :index]
      resources :invoices, only: [:index, :create]
      resources :permissions, only: [:show]

      namespace :billing do
        resources :plans, only: [:index]
        resources :payment_methods, only: [:new, :create, :index, :destroy]
        resources :subscriptions, only: [:show, :update, :destroy]
        resources :transactions, only: [:create, :index, :destroy]
        get '/plans/discounts', to: "plans#discounts"
      end

      resources :earned_memberships, only: [:show] do
        scope module: :earned_memberships do
          resources :reports, only: [:index, :create]
        end
      end

      namespace :admin  do
        resources :cards, only: [:new, :create, :index, :update]
        resources :invoices, only: [:index, :create, :update, :destroy]
        resources :invoice_options, only: [:create, :update, :destroy]
        resources :rentals, only: [:create, :update, :destroy, :index]
        resources :members, only: [:create, :update]
        resources :permissions, only: [:index, :update]
        namespace :billing do
          resources :subscriptions, only: [:index, :destroy]
          resources :transactions, only: [:show, :index, :destroy]
        end

        resources :earned_memberships, only: [:index, :show, :create, :update] do
          scope module: :earned_memberships do
            resources :reports, only: [:index]
          end
        end
      end
    end
  end

  get '*path', to: 'application#application'
end

app/views/layouts/_auth.html.erb
<% if member_signed_in? %>
Signed in as <%= current_member.fullname %>.
<%= link_to "Sign out", destroy_member_session_path, method: :delete, class: "btn btn-primary"  %>
<% else %>
<%= link_to "Sign in", new_member_session_path, class: "btn btn-primary"  %>
<% end %>
<br>

app/views/layouts/_navigation.html.erb
<div class="col-lg-12" id="navigation">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Manchester Makerspace</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Members", members_path, :class => 'navbar-link'  %> </li>
          <li><%= link_to "Workshops", workshops_path, :class => 'navbar-link'  %> </li>
          <li><%= link_to "Rentals", rentals_path, class: 'navbar-link' %></li>
          <% if is_admin? %>
            <li><%= link_to "New Member", new_admin_member_path, class: 'navbar-link' %></li>
            <li><%= link_to "Renew a Member", admin_renew_path, class: 'navbar-link' %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right" id="auth">
          <div class="navbar-link">
            <%= render 'layouts/auth' %>

          </div>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>

app/views/layouts/_search.html.erb
<form method='POST' action='/members/search_by'>
   <%= token_tag nil %>
	<label>Search Members:</label>
	 <select name='field'>
		 <% Member.search_terms.each do |attr| %>
				<% if attr == 'name' %>
					<option value='fullname' selected='selected'> Name </option>
				<% else %>
					<option value='<%=attr%>'><%=attr%></option>
				<% end %>
		<%end%>
		Value: <input type='text' name='value'>
		<input type='submit' name='Search'>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Makerspace Authorization</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'jquery-ui.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'member', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'skill', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'workshop', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>
<body>
  <div class="container">

    <div class="row">
      <%= render 'layouts/navigation' %>
    </div> <!--navbar row-->

    <div class='row'>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>
      <%= yield %>
  </div>

  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>

</body>
</html>