config/routes.rb
Rails.application.routes.draw do

  root to: "application#application"
  post '/ipnlistener', to: 'paypal#notify'
  namespace :billing do 
    post '/braintree_listener', to: 'braintree#webhooks'
  end

  scope :api, defaults: { format: :json } do
    devise_for :members, skip: [:registrations]
    devise_scope :member do
       post "members", to: "registrations#create"
       post '/send_registration', to: 'registrations#new'
    end
    resources :invoice_options, only: [:index]

    authenticate :member do
      resources :members, only: [:show, :index, :update]
      resources :rentals, only: [:show, :index]
      resources :invoices, only: [:index, :create]
      resources :permissions, only: [:show]

      namespace :billing do
        resources :plans, only: [:index]
        resources :payment_methods, only: [:new, :create, :index, :destroy]
        resources :subscriptions, only: [:show, :update, :destroy]
        resources :transactions, only: [:create, :index, :destroy]
        get '/plans/discounts', to: "plans#discounts"
      end

      resources :earned_memberships, only: [:show] do
        scope module: :earned_memberships do
          resources :reports, only: [:index, :create]
        end
      end

      namespace :admin  do
        resources :cards, only: [:new, :create, :index, :update]
        resources :invoices, only: [:index, :create, :update, :destroy]
        resources :invoice_options, only: [:create, :update, :destroy]
        resources :rentals, only: [:create, :update, :destroy, :index]
        resources :members, only: [:create, :update]
        resources :permissions, only: [:index, :update]
        namespace :billing do
          resources :subscriptions, only: [:index, :destroy]
          resources :transactions, only: [:show, :index, :destroy]
        end

        resources :earned_memberships, only: [:index, :show, :create, :update] do
          scope module: :earned_memberships do
            resources :reports, only: [:index]
          end
        end
      end
    end
  end

  get '*path', to: 'application#application'
end

app/models/member.rb
class Member
  include Mongoid::Document
  include Mongoid::Search
  include ActiveModel::Serializers::JSON
  include InvoiceableResource
  include Service::BraintreeGateway
  include Service::GoogleDrive
  include Service::SlackConnector

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  field :cardID

  #split first and last
  field :firstname
  field :lastname
  field :status,                         default: "activeMember" # activeMember, nonMember, revoked, inactive
  field :expirationTime,  type: Integer  #pre-calcualted time of expiration
  field :startDate, default: Time.now
  field :groupName #potentially member is in a group/partner membership
  field :role,                          default: "member" #admin,officer,member
  field :memberContractOnFile, type: Boolean
  field :subscription,    type: Boolean,   default: false
  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time
  ## Rememberable - Handles cookies
  field :remember_created_at, type: Time

  field :customer_id, type: String # Braintree customer relation
  field :subscription_id, type: String # Braintree relation

  search_in :email, :lastname
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, uniqueness: true
  validates :cardID, uniqueness: true, allow_nil: true
  validates_inclusion_of :status, in: ["activeMember", "nonMember", "revoked", "inactive"]
  validates_inclusion_of :role, in: ["admin", "member"]

  after_initialize :verify_group_expiry
  before_update :update_initial_expiration_from_invoice, :if => proc { !cardID && cardID_changed? }
  before_save :update_braintree_customer_info
  after_update :update_card
  after_create :apply_default_permissions, :send_slack_invite, :send_google_invite

  has_many :permissions, class_name: 'Permission', dependent: :destroy, :autosave => true
  has_many :rentals, class_name: 'Rental'
  has_many :invoices, class_name: "Invoice"
  has_many :access_cards, class_name: "Card", inverse_of: :member
  belongs_to :group, class_name: "Group", inverse_of: :active_members, optional: true, primary_key: 'groupName', foreign_key: "groupName"
  has_one :group, class_name: "Group", inverse_of: :member
  has_one :earned_membership, class_name: 'EarnedMembership', dependent: :destroy

  def self.search_members(searchTerms, criteria = Mongoid::Criteria.new(Member))
    members = criteria.where(email: searchTerms)
    members = Member.full_text_search(searchTerms).sort_by(&:relevance).reverse unless (members.size > 0)
    members = Member.full_text_search(searchTerms).sort_by(&:relevance).reverse unless (members.size > 0)
    return members
  end

  # Includes firstname if cant find anything else
  # Not to be used for Payment association
  def self.rough_search_members(searchTerms, criteria = Mongoid::Criteria.new(Member))
    members = self.search_members(searchTerms, criteria)
    memebrs = Member.full_text_search(searchTerms).sort_by(&:relevance).reverse unless (members.size > 0)
    return members
  end

  def fullname
    return "#{self.firstname} #{self.lastname}"
  end

  def verify_group_expiry
    if self.group
      #make sure member benefits from group expTime
      if benefits_from_group
        self.expirationTime = self.group.expiry
        self.save
      end
    end
  end

  # Find the subscribed resource (instance of Member | Rental) for member
  # Since subscriptions aren't stored in our db, we'll check the subscribed resources
  # to verify ownership
  def find_subscribed_resource(id)
    resource = self if self.subscription_id && self.subscription_id == id
    resource = self.rentals.detect { |r| r.subscription_id == id }  unless resource || self.rentals.nil?
    resource
  end

  def remove_subscription
    self.update_attributes!({ subscription_id: nil, subscription: false })
  end

  def get_permissions
    Hash[permissions.map { |p| [p.name.to_sym, p.enabled] }]
  end

  def update_permissions(permissions_collection)
    permissions_collection.each_pair do |name, enabled|
      permission = permissions.detect { |p| p.name == name.to_sym}
      if permission
        permission.update!(enabled: enabled)
      else
        Permission.new(name: name.to_sym, enabled: enabled, member_id: self.id).upsert
      end
    end
  end

  def is_allowed?(permission_name)
    permissions.detect { |p| p.name == permission_name.to_sym && !!p.enabled }
  end

  protected
  def base_slack_message
    self.fullname
  end

  def find_braintree_customer
    connect_gateway.customer.find(self.customer_id) unless self.customer_id.nil?
  end

  def update_braintree_customer_info
    if self.customer_id && self.changed.any? { |attr| [:firstname, :lastname].include?(attr) }
      connect_gateway.customer.update(self.customer_id, firstname: self.firstname, lastname: self.lastname)
    end
  end

  def expiration_attr
    :expirationTime
  end

  private
  def update_card
    self.access_cards.each do |c|
      c.update(expiry: self.expirationTime)
    end
  end

  # Update expiration by giving time back that has elapsed since signing up
  def update_initial_expiration_from_invoice
    start = startDate.to_i * 1000
    expirationTime ||= Time.now
    lag = expirationTime - start
    update!({ expirationTime: (expirationTime + lag)})
  end

  def benefits_from_group
    return self.group.expiry &&
           self.expirationTime &&
           self.group.expiry > (Time.now.strftime('%s').to_i * 1000) &&
           self.group.expiry > self.expirationTime
  end

  def email_required?
    false
  end

  def password_required?
    false
  end

  def send_slack_invite
    invite_to_slack()
  end

  def send_google_invite
    begin
      invite_gdrive(self.email)
    rescue Error::Google::Upload => err
      send_slack_message("Error sharing Member Resources folder with #{self.fullname}. Error: #{err}")
    end
  end

  def apply_default_permissions
    update_permissions(DefaultPermission.list_as_hash)
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < AdminController
  before_action :set_member, only: [:update]

  def create
    @member = Member.new(get_camel_case_params)
    @member.save!
    @member.reload
    send_set_password_email
    render json: @member and return
  end

  def update
    date = @member.expirationTime
    @member.update!(get_camel_case_params)
    notify_renewal(date)
    @member.reload
    render json: @member and return
  end

  private
  def member_params
    params.require(:member).permit(:firstname, :lastname, :role, :email, :status, :expiration_time, :renew, :member_contract_on_file)
  end

  def get_camel_case_params
    camel_case_props = {
      expiration_time: :expirationTime,
      member_contract_on_file: :memberContractOnFile,
    }
    params = member_params()
    camel_case_props.each do | key, value|
      params[value] = params.delete(key) unless params[key].nil?
    end
    params
  end

  def set_member
    @member = Member.find(params[:id])
    raise ::Mongoid::Errors::DocumentNotFound.new(Member, { id: params[:id] }) if @member.nil?
  end

  def notify_renewal(init)
    final = @member.expirationTime
    # Check if adding expiration too
    if final &&
        (init.nil? ||
        (Time.at(final / 1000) - Time.at((init || 0) / 1000) > 1.day))
      @messages.push(@member.get_renewal_slack_message)
    end
  end

  def send_set_password_email
    raw_token, hashed_token = ::Devise.token_generator.generate(Member, :reset_password_token)
    @member.reset_password_token = hashed_token
    @member.reset_password_sent_at = Time.now.utc
    @member.save!
    MemberMailer.welcome_email_manual_register(@member, raw_token).deliver_now
  end
end

app/controllers/members_controller.rb
class MembersController < AuthenticationController
    include FastQuery
    include ::Service::GoogleDrive
    before_action :set_member, only: [:show, :update]

    def index
      # Limit index to only current members unless authorized and requesting full records
      if is_admin? && (params[:currentMembers].nil? || params[:currentMembers].empty?)
        search = Mongoid::Criteria.new(Member)
      else
        # Include unset or expired within grace period
        search = Member.where({
          :$or => [
            { :expirationTime.gte => ((Time.now + 3.days).strftime('%s').to_i * 1000) },
            {  expirationTime: nil }
          ]
        })
      end
      @members = query_params[:search].nil? || query_params[:search].empty? ? search.all : Member.rough_search_members(query_params[:search], search)
      @members = query_resource(@members)

      return render_with_total_items(@members, root: :members)
    end

    def show
      render json: @member and return
    end

    def update
      # Non admins can only update themselves
      raise Error::Unauthorized.new unless @member.id == current_member.id

      if signature_params[:signature]
        begin
          encoded_img = signature_params[:signature].split(",")[1]
          upload_signature(encoded_img, "#{@member.fullname}_signature.png")
          @member.update_attributes!(memberContractOnFile: true)
        rescue Error::Google::Upload => err
          @messages.push("Error uploading #{@member.fullname}'s signature'. Error: #{err}")
        end
        render json: {}, status: 204 and return
      end

      @member.update_attributes!(member_params)
      render json: @member and return
    end

    private
    def set_member
      @member = Member.find(params[:id])
      raise ::Mongoid::Errors::DocumentNotFound.new(Member, { id: params[:id] }) if @member.nil?
    end

    def signature_params
      params.require(:member).permit(:signature)
    end

    def member_params
      params.require(:member).permit(:firstname, :lastname, :email)
    end
end

app/views/members/_form.html.erb
<div class="form-group">
<%= form_for [@workshop, @member] do |f| %>

  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% @member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag 'workshop_id', @workshop.id %>

  <div class="field">
    <h4><%= f.label :fullname %>
    <%= @member.fullname %> </h4>
  </div>


  <h4><%= f.label 'Skills:' %> </h4>
  <h5>Workshop: <%= f.label @workshop.name %> </h5>
  <div class="well">
    <%= f.collection_check_boxes(:learned_skill_ids, @workshop.skills, :id, :name) do |b| %>
      <ul>
				<%=  b.label(:"data-value" => b.value) { b.check_box + b.text } %>
      </ul>
    <% end %>
  </div>

  <br>
  <%= f.submit "Update User" %>
<% end %>

</div>

app/views/members/edit.html.erb
<h1>Train Member</h1>
<div class="well">
	<%= render "form" %>
</div>

app/views/members/index.html.erb
<%= render '/layouts/search' %>
<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>Name</th>
      <th>Allowed Workshops</th>
			<% if is_officer? || is_admin?%>
				<th>Membership Exp. Date</th>
			<%end%>
		</tr>
	</thead>
	<tbody>
		<% if @members.size == 0 %>
			<tr>
				<td colspan="6">No members found.</td>
			</tr>
		<% else %>
			<% @members.each do |member| %>
				<%if is_officer? || is_admin? %>
				<tr>
					<td><%= link_to "#{member.fullname}", member_path(member) %></td>
				<%else%>
				<tr class="<%=member.membership_status%>">
					<td><%= "#{member.fullname}"%></td>
				<%end%>
	        <td>
						<button id="<%=member.id%>" class='show_workshops'>Show Allowed Workshops</button>
						<div style="display:none;">
							<%= member.list_allowed_workshops %>
						</div>
					</td>
					<% if is_officer? || is_admin? %>
						<td class="<%=member.membership_status%>Color"><%=member.prettyTime.strftime("%m/%d/%Y") %></td>
					<%end%>
		   	</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/members/show.html.erb
<div class="row shadow memberPage" id="<%= @member._id%>">
  <div class="col-sm-12">
    <h2><%= @member.fullname %> </h2>
    <h3>Slack Handle: <%= @member.slackHandle || 'Needs Slack Handle added to db' %></h3>
    <h3>Email: <%= @member.email || 'Needs email added to db' %> </h3>
    <h4>Membership Expiration Date: <%= @member.prettyTime.strftime("%m/%d/%Y") %></h4>
    <% if !@member.offices.empty? %>
      <h4>Officer of: <%=@member.offices.pluck(:name).join(", ")%></h4>
    <%end%>
    <% if is_admin? %>
      <%= link_to "Edit", edit_admin_member_path(@member), class: "btn btn-primary card"  %>
    <% end %>

    <p></p>

      <% @workshops.each do |workshop| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class"panel-title">
            <%=workshop.name %> (Click to view required skills)
            <% if is_officer?(workshop) %>
              <% if workshop.experts.include?(@member) %>

              <% elsif @member.allowed_workshops.include?(workshop) %>
                <%= (link_to "MAKE EXPERT", workshop_member_path(workshop, @member),  class: "btn btn-info expert", id: "#{workshop.id}") %>
              <% else %>
                <%= (link_to "TRAIN", edit_workshop_member_path(workshop, @member),  class: "btn btn-success train", id: "#{workshop.id}")%>
              <% end %>
            <% end%>
        </h4>
      </div>
        <div class="panel-body" style='display: none;'>
          <% if workshop.skills.empty? %>
            <%= "No skills requried for #{workshop.name}" %>
          <% else %>
            <% workshop.skills.each do |skill| %>
              <li><%= skill.name %></li>
            <% end %>
          <% end %>
        </div>
      </div>
      <% end %>
  </div>
</div>